import { sql } from "drizzle-orm";
import { bigint, timestamp, uuid } from "drizzle-orm/pg-core";

/** Standard id column: uuid v4 generated by pgcrypto. */
export const idColumn = () =>
  uuid("id").primaryKey().default(sql`gen_random_uuid()`);

/** Standard timestamps. */
export const timestampColumns = {
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
};

/** Centavos column helper. Money is integer centavos, never floats, never pesos. */
export const centavos = (name: string) => bigint(name, { mode: "bigint" });
